Description: Cria bucket no S3

Resources:

  BucketBeliscoS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-vilela202103
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True